development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_TSL_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: bare_bone_staging

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_TSL_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: bare_bone_production
