default: &default
  cloud_name: <%= Credentials.get(:cloudinary, :cloud_name) %>
  api_key: <%= Credentials.get(:cloudinary, :api_key) %>
  api_secret: <%= Credentials.get(:cloudinary, :api_secret) %>
  enhance_image_tag: true
  static_file_support: false

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
